fail_fast: true

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-executables-have-shebangs
    - id: check-shebang-scripts-are-executable
    - id: check-symlinks
    - id: no-commit-to-branch

- repo: https://github.com/tomhoover/pre-commit-hooks
  rev: 3.0.0
  hooks:
    - id: forbid-binary
    - id: script-must-have-extension
    - id: shellcheck

- repo: https://github.com/tomhoover/pre-commit-hooks
  rev: 3.0.0
  hooks:
    - id: script-must-have-extension
      name: Local policy is to use .sh extension for shell scripts
      types: [shell, executable]

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
      language_version: python3.9

- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v3.0.0a5
  hooks:
    - id: pylint
      args: [--disable=all, --enable=unused-import]
