fail_fast: true

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-executables-have-shebangs
    - id: check-shebang-scripts-are-executable
    - id: check-symlinks
    - id: no-commit-to-branch

- repo: https://github.com/tomhoover/pre-commit-hooks
  rev: 3.0.0
  hooks:
    - id: forbid-binary
    - id: script-must-have-extension
    - id: shellcheck
#    - id: shfmt

- repo: https://github.com/tomhoover/pre-commit-hooks
  rev: 3.0.0
  hooks:
    - id: script-must-have-extension
      name: Local policy is to use .sh extension for shell scripts
      types: [shell, executable]

# python

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
      language_version: python3.9
#      args: [--diff, --check]

- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v3.0.0a5
  hooks:
    - id: pylint
      args: [--disable=all, --enable=unused-import]

# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v0.982
#   hooks:
#     - id: mypy
#       exclude: ^tests/
#       args: [--strict]

# no longer needed, as black ensures pep8 compliance
# - repo: https://github.com/pre-commit/mirrors-autopep8
#   rev: v2.0.0
#   hooks:
#     - id: autopep8

# the following was disabled, as it required docker to be running
# - repo: https://github.com/koalaman/shellcheck-precommit
#   rev: v0.8.0
#   hooks:
#     - id: shellcheck
# #     args: ["--severity=warning"]  # Optionally only show errors and warnings
